import type { Metadata } from "next";
import { Geist, Geist_Mono, Londrina_Shadow, Pacifico, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  subsets: ['cyrillic'],
  weight: ['400'],
  variable: '--font-pacifico'
});

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300"],
  variable: "--font-roboto",
});

const londrina = Londrina_Shadow({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-londrina",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${pacifico.variable} ${londrina.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
