import type { Metadata } from "next";
import { Geist, Geist_Mono, Londrina_Shadow, Pacifico, Roboto, Press_Start_2P, Play } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Head from "next/head";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  subsets: ['cyrillic'],
  weight: ['400'],
  variable: '--font-pacifico'
});

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300"],
  variable: "--font-roboto",
});

const londrina = Londrina_Shadow({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-londrina",
});

const pressStart2P = Press_Start_2P({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-press-start",
});

const play = Play({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-play",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta name="description" content="We develop first class softwares." />
        <title>Nohara Technologies</title>
      </Head>

      <html lang="en" className="h-full">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${pacifico.variable} ${londrina.variable} ${pressStart2P.variable} ${play.variable} relative`}
        >
          <Header />
          {children}
        </body>
      </html>
    </>
  );
}
